# Generated by Django 3.2.12 on 2022-03-11 07:41

import uuid

import api.coupons.models

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.PositiveSmallIntegerField(
                        help_text="Amount in cents", validators=[api.coupons.models.validate_amount]
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.UniqueConstraint(fields=("amount",), name="unique_amount"),
        ),
    ]
