# Generated by Django 3.2.12 on 2022-03-18 08:26

import api.coupons.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coupon",
            name="unique_amount",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Amount in cents",
                unique=True,
                validators=[api.coupons.validators.validate_amount],
            ),
        ),
    ]
