# Generated by Django 3.2.12 on 2022-03-18 08:35

import uuid

import api.coupons.validators

import django.db.models.deletion
import django.utils.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coupons", "0002_auto_20220318_0826"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="amount",
            field=models.PositiveSmallIntegerField(
                choices=[(500, "500"), (1000, "1000"), (1500, "1500")],
                help_text="Amount in cents",
                unique=True,
                validators=[api.coupons.validators.validate_amount],
            ),
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(default=django.utils.crypto.get_random_string, max_length=16),
                ),
                ("valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_coupons",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="usercoupon",
            constraint=models.UniqueConstraint(
                condition=models.Q(("valid", True)),
                fields=("valid", "user", "coupon"),
                name="unique_valid_user_coupon",
            ),
        ),
    ]
