# Generated by Django 3.2.12 on 2022-03-21 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0003_auto_20220318_0835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoupon",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
