global:
  scrape_interval: 10s
  
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

rule_files:
- /etc/prometheus/rules.yml

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100

- job_name: web-apps
  static_configs:
  - targets:
    - app:8000