{
 "title": "Web App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "user", "label": "User", "query": "label_values(user)" },
   { "name": "method", "label": "Method", "query": "label_values(method)" },
   { "name": "endpoint", "label": "Endpoint", "query": "label_values(endpoint)" }
  ]
 },
 "panels": [
  {
   "title": "App info",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_info" }
   ]
  },
  {
   "title": "Total \"GET\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"GET\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Total \"POST\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"POST\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "Total \"PATCH\"",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(app_requests_total{method=\"PATCH\", user=~\"$user\", endpoint=~\"$endpoint\"})"
    }
   ]
  },
  {
   "title": "API calls",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "app_requests_total{user=~\"$user\", method=~\"$method\", endpoint=~\"$endpoint\"}"
    }
   ]
  },
  {
   "title": "Last activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "app_last_user_activity_time_seconds{}*1000"
    }
   ]
  },
  {
   "title": "Page visits/s  FIX ME",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user) (sum by (endpoint) (rate(app_requests_total{}[1m])))"
    }
   ]
  },
  {
   "title": "Coupon creating time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Time [s]" }
   ],
   "targets": [
    {
     "expr": "rate(app_coupon_create_time_seconds_sum[1m])/rate(app_coupon_create_time_seconds_count[1m])",
     "legendFormat": "time"
    }
   ]
  }
 ]
}